spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=pwd
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=INFO
